name: 'extract modrinth app'

on: 
  workflow_dispatch:
    inputs:
      download-url:
        type: text
        required: true
        description: URL to the installer

jobs:
  extract:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Download Modrinth App'
        run: |-
          echo "Download URL from: $DOWNLOAD_URL"
          wget "$DOWNLOAD_URL" -O installer.exe
        env:
          DOWNLOAD_URL: ${{ github.event.inputs.download-url }}
      - name: 'Extract the file'
        run: |-
          7z x installer.exe "Modrinth App.exe"
      - name: 'Upload'
        uses: actions/upload-artifact@v4.3.3
        with:
          name: 'Extracted file'
          path: "Modrinth App.exe"
        
